### ISSUE TITLE
Broken Links to USC Pages

### ISSUE THREAD

**Issue by TheRealMJP** [hpd/DigitalEmily#1]
Hey there,

First of all, thank you for making this repository! It's a great asset to have available for research.

I noticed that the links to ict.usc.edu sites in the readme(s) currently produce a "Page not found error", I believe this is because they now need to be prefixed with `vgl.`. So for example `https://ict.usc.edu/Research/DigitalEmily2/` should be `https://vgl.ict.usc.edu/Data/DigitalEmily2/`. 

-Matt

**Comment by hpd** [comment]
Updated. Thanks for the heads up.
